package ru.burmistrov.soap.api.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-06-06T17:24:26.203+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.api.soap.burmistrov.ru/", name = "IUserEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface IUserEndpoint {

    @WebMethod
    @RequestWrapper(localName = "findOneUserById", targetNamespace = "http://endpoint.api.soap.burmistrov.ru/", className = "ru.burmistrov.soap.api.endpoint.FindOneUserById")
    @ResponseWrapper(localName = "findOneUserByIdResponse", targetNamespace = "http://endpoint.api.soap.burmistrov.ru/", className = "ru.burmistrov.soap.api.endpoint.FindOneUserByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.burmistrov.soap.api.endpoint.User findOneUserById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @WebMethod
    @RequestWrapper(localName = "removeUserById", targetNamespace = "http://endpoint.api.soap.burmistrov.ru/", className = "ru.burmistrov.soap.api.endpoint.RemoveUserById")
    @ResponseWrapper(localName = "removeUserByIdResponse", targetNamespace = "http://endpoint.api.soap.burmistrov.ru/", className = "ru.burmistrov.soap.api.endpoint.RemoveUserByIdResponse")
    public void removeUserById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @WebMethod
    @RequestWrapper(localName = "updateUserById", targetNamespace = "http://endpoint.api.soap.burmistrov.ru/", className = "ru.burmistrov.soap.api.endpoint.UpdateUserById")
    @ResponseWrapper(localName = "updateUserByIdResponse", targetNamespace = "http://endpoint.api.soap.burmistrov.ru/", className = "ru.burmistrov.soap.api.endpoint.UpdateUserByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.burmistrov.soap.api.endpoint.User updateUserById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id,
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @WebMethod
    @RequestWrapper(localName = "findAllUsers", targetNamespace = "http://endpoint.api.soap.burmistrov.ru/", className = "ru.burmistrov.soap.api.endpoint.FindAllUsers")
    @ResponseWrapper(localName = "findAllUsersResponse", targetNamespace = "http://endpoint.api.soap.burmistrov.ru/", className = "ru.burmistrov.soap.api.endpoint.FindAllUsersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.burmistrov.soap.api.endpoint.User> findAllUsers();

    @WebMethod
    @RequestWrapper(localName = "createUser", targetNamespace = "http://endpoint.api.soap.burmistrov.ru/", className = "ru.burmistrov.soap.api.endpoint.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://endpoint.api.soap.burmistrov.ru/", className = "ru.burmistrov.soap.api.endpoint.CreateUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.burmistrov.soap.api.endpoint.User createUser(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );
}
